apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: test-model
  namespace: default
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "gs://kfserving-examples/models/sklearn/1.0/model"
